Repository Saphirac/minishell, pull requests merged in 2023-03, with the labels that each got.

#13 Update the type of the exit status code
  include/minishell.h
  src/main.c
Labels: enhancement

#15 Classify tokens
  Makefile
  include/list.h
  include/minishell.h
  src/env/env_lst/env_lst_add_back.c
  src/env/env_lst/env_lst_add_front.c
  src/env/env_lst/env_lst_clear.c
  src/env/env_lst/env_lst_del_one.c
  src/env/env_lst/env_lst_print.c
  src/env/env_lst/env_lst_push_back.c
  src/env/env_lst/env_lst_push_front.c
  src/env/env_lst/env_new.c
  src/main.c
  src/tokens/classify_tokens.c
  src/tokens/classify_tokens_utils.c
  src/tokens/get_tokens.c
  src/tokens/tokens_operators.c
Labels: enhancement, add

#27 Cmd builtin pipeline
  Makefile
  include/minishell.h
  include/shell.h
  src/here_doc/here_tokens.c
  src/main.c
  src/prompt.c
  src/tokens/classify_tokens.c
  src/tokens/final_classification.c
Labels: add

#31 Fix the cd builtin behavior when giving a relative path as destination
  src/builtin/cd/raw_curpath.c
Labels: fix
