Repository Saphirac/minishell, pull requests merged in 2023-04, with the labels that each got.

#33 Implement additional redirections
  Makefile
  include/list.h
  include/lookup_builtin.h
  include/minishell.h
  include/shell.h
  src/builtin/echo/core.c
  src/env/lst/env_lst_del_one.c
  src/exec/core.c
  src/exec/pid/lst/pid_lst_del_one.c
  src/exec/redirections.c
  src/main.c
  src/tokens/lst_tokens/token_lst_del_one.c
  src/tokens/lst_tokens/token_lst_del_range.c
  src/tokens/lst_tokens/token_lst_is_first_builtin.c
  src/util/error/usage_error.c
Labels: add

#39 Final classification [OK]
  include/minishell.h
  src/prompt.c
  src/tokens/classify_tokens.c
  src/tokens/classify_tokens_utils.c
  src/tokens/expand_tokens.c
  src/tokens/final_classification.c
  src/tokens/split_spaces.c
Labels: enhancement

#42 Here doc + Fix lst changes
  include/minishell.h
  src/here_doc/here_doc.c
  src/here_doc/here_tokens.c
  src/prompt.c
  src/tokens/append_to_ret.c
  src/tokens/final_classification.c
  src/tokens/search_env.c
  src/tokens/split_spaces.c
Labels: enhancement, add, fix

#44 Fix the broken pipe wrong behavior
  Makefile
  include/list.h
  include/minishell.h
  src/exec/core.c
  src/exec/pid/lst/pid_lst_kill.c
  src/exec/pid/lst/pid_lst_wait.c
  src/exec/pipeline.c
  src/exec/run.c
Labels: fix

#46 Signals
  include/enum.h
  include/minishell.h
  src/exec/core.c
  src/exec/file_redirections.c
  src/exec/pid/lst/pid_lst_wait.c
  src/exec/pipeline.c
  src/here_doc/here_doc.c
  src/main.c
  src/prompt.c
  src/signals.c
  src/tokens/expand_tokens.c
Labels: enhancement, add, fix

#47 Use perror
  Makefile
  include/minishell.h
  src/builtin/cd/core.c
  src/builtin/cd/raw_curpath.c
  src/builtin/echo/core.c
  src/builtin/export/process_one.c
  src/builtin/pwd/core.c
  src/exec/core.c
  src/exec/pid/lst/pid_lst_wait.c
  src/exec/pipeline.c
  src/exec/run.c
  src/util/error/internal_error.c
Labels: enhancement

#48 Prevent exiting the shell when any error occurs in builtins
  include/lookup_builtin.h
  include/minishell.h
  src/builtin/cd/core.c
  src/builtin/echo/core.c
  src/builtin/env/core.c
  src/builtin/exit/core.c
  src/builtin/export/core.c
  src/builtin/export/surprise.c
  src/builtin/pwd/core.c
  src/builtin/unset/core.c
  src/exec/core.c
  src/exec/pipeline.c
  src/exec/run.c
Labels: enhancement
